Repository waterloop/teamhub, pull requests merged in 2019-11, with the labels that each got.

#16 Add contributing section
  README.md
Labels: ready-to-merge

#15 [WIP] Initial page layout with member list
  components/atoms/BorderlessButton.js
  components/atoms/Button.js
  components/atoms/Card.js
  components/atoms/GhostButton.js
  components/atoms/Header3.js
  components/atoms/Icons/MailIcon.js
  components/atoms/Logo.js
  components/atoms/Svg.js
  components/molecules/MemberFilterComponent.js
  components/molecules/MemberInfoCard.js
  components/molecules/MemberListGrid.js
  components/molecules/MemberPreviewComponent.js
  components/molecules/Nav.js
  components/organisms/MyHub.js
  components/templates/PageTemplate.js
  components/theme.js
  data/api/services/memberService.js
  data/reducers/memberSlice.js
  package-lock.json
  pages/_document.js
  pages/index.js
  static/baseline-mail-24px.svg
  static/default-headshot.png
  static/linkIcon.png
Labels: wip

#36 Updated Mongodb testing
  README.md
  backend/data/config.template.json
  backend/data/config.tests.json
  backend/data/index.js
  backend/data/scripts/addMemberType.js
  backend/data/scripts/addProject.js
  backend/data/scripts/addSkill.js
  backend/data/scripts/addSubteam.js
  backend/data/scripts/test-data.js
  docker/mongodb/docker-entrypoint-initdb.d/import.sh
  package.json
  tests/Api.test.js
  tests/Members.test.js
  tests/Utils.test.js
Labels: backend, testing
